"""
This module creates the graphs from the data frame generated by calculate.py
"""

from calculate import *
from plotly.offline import plot
import plotly.express as px

def draw_scatterplot(df, x='Date', y='DLI'):
    fig = px.scatter(df, x, y, trendline='ols')

    fig.update_traces(
    line=dict(dash="dot", width=4),
    selector=dict(type="scatter", mode="lines"))

    plot(fig, auto_open=True)

if __name__ =="__main__":
    ppfd_df = calculate_ppfd(create_df(4,5,2010,10,17,2010))
    # dli_df = calculate_dli(ppfd_df)
    # dli_df.to_csv('data.csv', index = True)
    # draw_scatterplot(dli_df, x='PAR', y='DLI')

    # dli_df.to_csv('data.csv', index = True)
    draw_scatterplot(ppfd_df)
    draw_scatterplot(ppfd_df, x='Date', y='DLI')
